config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'posts#index'
  resources :posts do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  validates :content, presence: true, allow_blank: false
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :comments, dependent: :destroy
    # validates :user_id, presence: true
    validates :image, presence: true
    has_attached_file :image, styles: { :medium => "640px" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_post
    
    def create
        @comment = @post.comments.build(comment_params)
        @comment.user_id = current_user.id
       
        if @comment.save
            flash[:success] = "The comment has been submitted successfully!"
            redirect_to root_path
        else
            flash[:danger] = "There was an error submitting the comment"
            redirect_to root_path
        end
    end
    
    def destroy
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to root_path
    end
    
    def comment_params
        params.require(:comment).permit(:content)
    end
    
    def set_post  
        @post = Post.find(params[:post_id])
    end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    # before_action :authenticate_user!
    
    def index
        @posts = Post.all
    end
    
    def new
        if user_signed_in?
            @post = current_user.posts.build
        else
            @post = Post.new
        end
    end
    
    def create
        if user_signed_in?
            @post = current_user.posts.build(post_params)
            
            if @post.save
                flash[:success] = "Successful Upload"
                redirect_to posts_path
            else
                flash[:danger] = "Upload Failed"
                render :new
            end
        else
            if @post = Post.create(post_params)
              flash[:success] = "Your post has been created!"
              redirect_to posts_path
            else
              flash.now[:alert] = "Your new post couldn't be created!  Please check the form."
              render :new
            end
        end
    end
    
    def destroy  
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to root_path
    end
    
    def post_params
        params.require(:post).permit(:image, :caption)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
        def sign_up_params
            params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
        end
        
        def account_update_params
            params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Navbar bootstrap -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <i class="fa fa-camera-retro" aria-hidden="true"></i> INSTAphoto
        <% end %>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <%= link_to "Create a Post", new_post_path, class: 'btn btn-default navbar-btn' %>
          <% if user_signed_in? %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger navbar-btn' %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success navbar-btn' %>
            <%= link_to "Sign In", new_user_session_path, class: 'btn btn-default navbar-btn' %>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  
  <div class="container">
    <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{type}" %>
    <% end %>
  </div>
  
  <title>Instaphoto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="posts-wrap row">
        <div class="col-md-4 col-md-offset-4">
            <div class="post">
                <div class="post-head">
                    <div class="name">
                        <% if post.user %>
                            <%= post.user.user_name %>
                        <% else %>
                            Guest
                        <% end %>
                    </div>
                </div>
            </div>
            
            <div class="image center-block">
                <%= image_tag post.image.url(:medium), class:'img-responsive' %>
            </div>
            
            <div class="post-bottom">
                
                <div class="caption">
                    <%= post.caption %>
                </div>
                
                <% if post.user %>
                    <% if current_user %>
                        <% if post.user.id == current_user.id %>
                            <div class="delete-post">
                                <%= link_to "Delete Post", post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
                            </div>
                        <% end %>
                    <% end %>
                <% end %>
                
                
                <!-- Comments -->
                <% if post.comments %>
                    <% post.comments.each do |comment| %>
                        <div class="comment">
                            <div class="user-name">
                                <%= comment.user.user_name + ":" %>
                            </div>
                            
                            <div class="comment-content">
                                <%= comment.content %>
                            </div>
                            <% if user_signed_in? %> 
                                <% if comment.user == current_user %>
                                    <div class="delete-comment">
                                        <%= link_to "Delete", post_comment_path(post, comment), method: :delete %>
                                    </div>
                                <% end %>
                            <% end %>
                        </div>
                    <% end %>
                <% end %>
                
                <% if user_signed_in? %>
                    <%= form_for [post, post.comments.new] do |f| %>
                        <%= f.text_field :content, placeholder: 'Add a comment...', class: 'form-group form-control'%>
                    <% end %>
                <% end %>
            </div>
            
        </div>
    </div>
<% end %>

app/views/posts/new.html.erb
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h1> Upload Image and Caption </h1>
        <%= simple_form_for @post do |f| %>
            <div class="form-group">
                <%= f.input :image, as: :file %>
            </div>
                
            <div class="form-group">
                <%= f.input :caption %>
            </div>
                
            <div class="form-group text-center">
                <%= f.button :submit, class: 'btn btn-success' %>
            </div>
        <% end %>
    </div>
</div>